version: '3'

volumes:
  dist:
  webhook_var:


services:
  dev-compiler:
    environment:
      - DONT_RUN=${WEBHOOK_PORT-}
      - DEV=${DEV-false}
    build:
      context: .
      dockerfile: compiler.Dockerfile

    volumes:
      - ../seampan:/app/seampan:ro
      - ../barbet:/app/barbet:rw
      - ${DIST:-dist}:/output:rw
  webhook:
    privileged: true
    restart: on-failure
    build:
      context: .
      dockerfile: webhook.Dockerfile
    environment:
      - DO_RUN=${WEBHOOK_PORT-}
      - GITHUB_SECRET=${GITHUB_SECRET-}
    volumes:
      - ${DIST:-dist}:/output:rw
      - webhook_var:/var:rw
    ports:
      - ${WEBHOOK_PORT:-0}:3000
  server:
    environment:
      - SERVE=${SERVE-}
    build:
      context: .
      dockerfile: server.Dockerfile
    ports:
      - ${SERVE:-0}:80
    volumes:
      - ${DIST:-dist}:/app:ro
