version: '3'

volumes:
  dist:
  webhook_var:


services:
  webhook:
    privileged: true
    restart: always
    build:
      context: .
      dockerfile: webhook.Dockerfile
    volumes:
      - ${DIST:-dist}:/output:rw
      - webhook_var:/var:rw
    ports:
      - ${WEBHOOK_PORT:-0}:3000
  server:
    environment:
      - SERVE=${SERVE-}
    build:
      context: .
      dockerfile: server.Dockerfile
    ports:
      - ${SERVE:-3000}:80
    volumes:
      - ${DIST:-dist}:/app:ro
