version: '3'

volumes:
  dist:

services:
  compiler:
    environment:
      - DEV=${DEV-false}
    build: 
      context: .
      dockerfile: compiler.Dockerfile
    networks:
      - no-internet
    volumes:
      - ../seampan:/app/seampan:ro
      - ./src:/app/barbet/src:rw
      - ${DIST:-dist}:/output:rw
  server:
    environment:
      - SERVE=${SERVE}
    build: 
      context: .
      dockerfile: server.Dockerfile
    ports:
      - ${SERVE:-3000}:80
    volumes:
      - ${DIST:-dist}:/app:ro



networks:
  no-internet:
    driver: bridge
    internal: true