import * as imported_3 from "@3d/gpu-resources/program";import * as imported_2 from "@3d/gpu-resources/program";import * as imported_1 from "@3d/gpu-resources/program";import * as imported_0 from "@3d/gpu-resources/program";
  /*
  * THIS FILE WAS AUTOGENERATED, DO NOT CHANGE IT
  * Any change you make here will be overwritten by a compiler
  * edit appropriate .2bc.json file instead
  */
 export const enum ModelAttributeType{Uint,Vec3_N,Vec3F,UVec3_2,};export const getGlslNameByType = (value: ModelAttributeType) => { /* This file was autogenerated, don't change */
 switch (value) {case ModelAttributeType.Uint: return "uint";case ModelAttributeType.Vec3_N: return "vec3";case ModelAttributeType.Vec3F: return "vec3";case ModelAttributeType.UVec3_2: return "uvec3";default: throw new Error();}};export const getCountByType = (value: ModelAttributeType) => { /* This file was autogenerated, don't change */
 switch (value) {case ModelAttributeType.Uint: return 1;case ModelAttributeType.Vec3_N: return 3;case ModelAttributeType.Vec3F: return 3;case ModelAttributeType.UVec3_2: return 3;default: throw new Error();}};export const shouldNormalize = (value: ModelAttributeType) => { /* This file was autogenerated, don't change */
 switch (value) {case ModelAttributeType.Uint: return false;case ModelAttributeType.Vec3_N: return true;case ModelAttributeType.Vec3F: return false;case ModelAttributeType.UVec3_2: return false;default: throw new Error();}};export const getAttrTypeByType = (value: ModelAttributeType) => { /* This file was autogenerated, don't change */
 switch (value) {case ModelAttributeType.Uint: return imported_0.AttrType.UByte;case ModelAttributeType.Vec3_N: return imported_1.AttrType.UByte;case ModelAttributeType.Vec3F: return imported_2.AttrType.Float;case ModelAttributeType.UVec3_2: return imported_3.AttrType.UShort;default: throw new Error();}};