import * as imported_2 from './entity/slime'
import * as imported_1 from './entity/slime'
import * as imported_0 from './entity/slime'
/*
 * THIS FILE WAS AUTOGENERATED, DO NOT CHANGE IT
 * Any change you make here will be overwritten by a compiler
 * edit appropriate .2bc.json file instead
 */
export const enum ModelId {
  Slime_Idle,
  Slime_Jump,
  Slime_SlowlyRotating,
  SIZE,
}
export const getBuildModelCallback = (value: ModelId) => {
  /* This file was autogenerated, don't change */
  switch (value) {
    case ModelId.Slime_Idle:
      return imported_0.constructIdle
    case ModelId.Slime_Jump:
      return imported_1.constructJumping
    case ModelId.Slime_SlowlyRotating:
      return imported_2.constructSlowlyRotating
    default:
      throw new Error()
  }
}
