import * as imported_3 from './slime/jump'
import * as imported_2 from './slime/slow-rotate'
import * as imported_1 from './slime/idle'
import * as imported_0 from './none'
/*
 * THIS FILE WAS AUTOGENERATED, DO NOT CHANGE IT
 * Any change you make here will be overwritten by a compiler
 * edit appropriate .2bc.json file instead
 */
export const enum ActivityId {
  None,
  Slime_Idle,
  Slime_SlowRotate,
  Slime_Jump,
}
export const getActivityPerformFunction = (value: ActivityId) => {
  /* This file was autogenerated, don't change */
  switch (value) {
    case ActivityId.None:
      return imported_0.perform
    case ActivityId.Slime_Idle:
      return imported_1.perform
    case ActivityId.Slime_SlowRotate:
      return imported_2.perform
    case ActivityId.Slime_Jump:
      return imported_3.perform
    default:
      throw new Error()
  }
}
