on:
  push:
    branches: ["master"]

  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v3.5.1
      - name: Set up Docker Compose
        uses: docker/setup-compose-action@v1
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: docker compose up --build
        env:
          DIST: /tmp/wonder-dist
          DEV: false
          SERVE:
        working-directory: "encytem"
      - name: Deploy to Cloudflare Pages
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy /tmp/wonder-dist --project-name=${{ secrets.PROJECT_NAME }}
